#!/usr/bin/env python
# -*- coding: utf-8 -*-

__appname__ = "Stalone Tray Clock"
__version__ = "0.5"
__author__  = "Alexandre C Vieira"
__license__ = "GNU GPL 2.0 or later"

import pygtk
pygtk.require('2.0')
import gtk, gobject, datetime, calendar, configparser, io, os, locale, threading, time
from Xlib import display

UPDATE_INTERVAL = 1  # in Seconds
SHOW_CALENDAR = False
calendar_window = None
window_event = 0

def set_update_date_interval():
    now = datetime.datetime.now().strftime("%H:%M:%S")
    midnight = '00:00:00'
    FMT = '%H:%M:%S'
    delta = datetime.datetime.strptime(midnight, FMT) - datetime.datetime.strptime(now, FMT)
    return delta.seconds

def mousepos():
    """mousepos() --> (x, y) get the mouse coordinates on the screen (linux, Xlib)."""
    data = display.Display().screen().root.query_pointer()._data
    return data["root_x"], data["root_y"]

def day_of_week(date):
    return calendar.day_abbr[date.weekday()].capitalize()

def current_month(monthNumber):
    return calendar.month_abbr[monthNumber].capitalize()

def tooltip_text():
    today = datetime.date.today()
    dayofweek = calendar.day_name[today.weekday()].capitalize()
    day = str(today.day)
    month = calendar.month_name[today.month].capitalize()
    year = str(today.year)
    if LANG == 'pt':
        return dayofweek + ', ' + day + ' de ' + month + ' de ' + year
    else:
        return dayofweek + ', ' + day + ' ' + month + ' ' + year

def draw_window(label):
    widget = gtk.Layout()
    if label != None:
        widget.put(label,0,ICON_SIZE / 4)
    widget.show()
    window = gtk.OffscreenWindow()
    window.set_default_size(ICON_SIZE, ICON_SIZE)
    window.set_opacity(0)
    window.add(widget)
    window.show_all()
    col = gtk.gdk.Color(BGCOLOR)
    if label == None:
        window.present()
    widget.modify_bg(gtk.STATE_NORMAL, col)
    return window

def draw_calendar_window():
    global SHOW_CALENDAR
    SHOW_CALENDAR = True
    vbox = gtk.VBox(False, 5)
    cal = gtk.Calendar()
    cal.set_display_options(gtk.CALENDAR_SHOW_HEADING | gtk.CALENDAR_SHOW_DAY_NAMES)
    halign1 = gtk.Alignment(0.5, 0.5, 0, 0)
    halign1.add(cal)
    valign = gtk.Alignment(0, 1, 0, 0)
    vbox.pack_start(halign1)
    window = gtk.Window()
    window.set_decorated(False)
    window.set_size_request(250, 200)
    window.set_icon(gtk.icon_theme_get_default().load_icon("calendar", 48, 0))
    mouse = mousepos()
    window.move(mouse[0] - 125, mouse[1] + 30)
    window.add(vbox)
    window.connect("destroy", set_show_calendar)
    window.connect("visibility-notify-event", calendar_frame_event)
    window.show_all()
    return window

def set_show_calendar(gtkobject, data=None):
    global SHOW_CALENDAR
    SHOW_CALENDAR = False

def calendar_frame_event(window, event):
    global window_event
    if event.state == gtk.gdk.VISIBILITY_PARTIAL or event.state == gtk.gdk.VISIBILITY_FULLY_OBSCURED:
        window_event += 1
        if  window_event == 2:
            window_event = 0
            window.destroy()
    
def save_config():
    with open(os.path.expanduser('~/.stalone_tray_clockrc'), 'w') as f:
        f.write('%s\n%s\n%s\n%s\n%s\n%s' % ('icon_size' + ':'
                                                + str(ICON_SIZE), 'bgcolor' + ':' + BGCOLOR, 'fontcolor' + ':'
                                                + FONTCOLOR, 'fontsize' + ':' + FONTSIZE, 'font' + ':'
                                                + FONT, 'fontweight' + ':' + FONTWEIGHT))

def cb_allocate(label, allocation):
    label.set_size_request( ICON_SIZE, -1 )

def on_left_click(event):
    global SHOW_CALENDAR
    global calendar_window
    if not SHOW_CALENDAR:
        calendar_window = draw_calendar_window()
    else:
        calendar_window.destroy()
    
class ClockDayOfWeek:
    def __init__(self):
        self.icon = gtk.StatusIcon()
        self.icon.connect( "activate", on_left_click )
        self.label = gtk.Label()
        self.label.set_justify(gtk.JUSTIFY_CENTER)
        self.window = draw_window(self.label)
        self.window.connect("damage-event", self.draw_complete_event)
        self.update_day_of_week()
        global UPDATE_DATE_INTERVAL
         
    def update_day_of_week(self):
        self.icon.set_tooltip(tooltip_text())
        self.dayofweek = day_of_week(datetime.date.today())
        if LANG == 'pt':
            self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                                  + '\' font=\'' + FONT + '\'>' + self.dayofweek + ', </span>')
        else:
            self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                                  + '\' font=\'' + FONT + '\'>' + self.dayofweek + '</span>')
        self.label.connect( "size-allocate", cb_allocate )
        self.window.present()
        threading.Timer(UPDATE_DATE_INTERVAL, self.update_day_of_week).start()

    def draw_complete_event(self, window, event):
        self.icon.set_from_pixbuf(window.get_pixbuf())

class ClockDay:
    def __init__(self):
        self.icon = gtk.StatusIcon()
        self.icon.connect( "activate", on_left_click )
        self.label = gtk.Label()
        self.label.set_justify(gtk.JUSTIFY_CENTER)
        self.window = draw_window(self.label)
        self.window.connect("damage-event", self.draw_complete_event)
        self.update_day()
        global UPDATE_DATE_INTERVAL
        
    def update_day(self):
        self.icon.set_tooltip(tooltip_text())
        UPDATE_DATE_INTERVAL = set_update_date_interval()
        self.now = datetime.datetime.now()
        if LANG == 'pt':
            self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                                  + '\' font=\'' + FONT + '\'>' + str(self.now.day) + ' de</span>')
        else:
            self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                                  + '\' font=\'' + FONT + '\'>' + str(self.now.day) + ', </span>')
        self.label.connect( "size-allocate", cb_allocate )
        self.window.present()
        threading.Timer(UPDATE_DATE_INTERVAL, self.update_day).start()
    
    def draw_complete_event(self, window, event):
        self.icon.set_from_pixbuf(window.get_pixbuf())

class ClockMonth:
    def __init__(self):
        self.icon = gtk.StatusIcon()
        self.icon.connect( "activate", on_left_click )
        self.label = gtk.Label()
        self.label.set_justify(gtk.JUSTIFY_CENTER)
        self.window = draw_window(self.label)
        self.window.connect("damage-event", self.draw_complete_event)
        self.update_month()
        global UPDATE_DATE_INTERVAL
       
    def update_month(self):
        self.icon.set_tooltip(tooltip_text())
        self.month = current_month(datetime.date.today().month)
        self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                              + '\' font=\'' + FONT + '\'>' + self.month + '</span>')
        self.label.connect( "size-allocate", cb_allocate )
        self.window.present()
        threading.Timer(UPDATE_DATE_INTERVAL, self.update_month).start()

    def draw_complete_event(self, window, event):
        self.icon.set_from_pixbuf(window.get_pixbuf())

class ClockTime:
    def __init__(self):
        self.icon = gtk.StatusIcon()
        self.icon.connect( "activate", on_left_click )
        self.label = gtk.Label()
        self.label.set_markup('<span color="white">time</span>')
        self.label.set_justify(gtk.JUSTIFY_CENTER)
        self.window = draw_window(self.label)
        self.window.connect("damage-event", self.draw_complete_event)
        self.update_clock()
        global UPDATE_INTERVAL
                         
    def update_clock(self):
        self.now = datetime.datetime.now()
        if LANG == 'pt':
            self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                                  + '\' font=\'' + FONT + '\'>' + self.now.strftime("%H:%M") + '</span>')
        else:
            self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                                  + '\' font=\'' + FONT + '\'>' + self.now.strftime("%I:%M") + '</span>')
        self.label.connect( "size-allocate", cb_allocate )
        self.window.present()
        threading.Timer(UPDATE_INTERVAL, self.update_clock).start()

    def draw_complete_event(self, window, event):
        self.icon.set_from_pixbuf(window.get_pixbuf())

class ClockTimeAMPM:
    def __init__(self):
        self.icon = gtk.StatusIcon()
        self.icon.connect( "activate", on_left_click )
        self.label = gtk.Label()
        self.label.set_markup('<span color="white">time</span>')
        self.label.set_justify(gtk.JUSTIFY_CENTER)
        self.window = draw_window(self.label)
        self.window.connect("damage-event", self.draw_complete_event)
        self.update_clock()
        global UPDATE_INTERVAL
        self.now = None
                   
    def update_clock(self):
        self.now = datetime.datetime.now()
        self.label.set_markup('<span color=\'' + FONTCOLOR + '\' font_weight=\'' + FONTWEIGHT
                              + '\' font=\'' + FONT + '\'>' + self.now.strftime("%p") + '</span>')
        self.label.connect( "size-allocate", cb_allocate )
        self.window.present()
        threading.Timer(UPDATE_INTERVAL, self.update_clock).start()

    def draw_complete_event(self, window, event):
        self.icon.set_from_pixbuf(window.get_pixbuf())

class ClockPadding:
    def __init__(self):
        self.icon = gtk.StatusIcon()
        window = draw_window(None)
        window.connect("damage-event", self.draw_complete_event)

    def draw_complete_event(self, window, event):
        self.icon.set_from_pixbuf(window.get_pixbuf())
       
if __name__ == "__main__":
    gobject.threads_init()

    UPDATE_DATE_INTERVAL = set_update_date_interval()
    
    try:
        user_config_dir = open(os.path.expanduser('~/.stalone_tray_clockrc'), 'r').read().split('\n')
        ICON_SIZE = int(user_config_dir[0].split(':')[1])
        BGCOLOR = user_config_dir[1].split(':')[1]
        FONTCOLOR = user_config_dir[2].split(':')[1]
        FONTSIZE = user_config_dir[3].split(':')[1]
        FONT = user_config_dir[4].split(':')[1]
        FONTWEIGHT = user_config_dir[5].split(':')[1] # One of 'ultralight', 'light', 'normal', 'bold',
                                                      # 'ultrabold', 'heavy', or a numeric weight
        LANG = user_config_dir[6].split(':')[1]
    except IOError:
        ICON_SIZE = 32
        BGCOLOR = '#111'
        FONTCOLOR = 'white'
        FONTSIZE = '9.5'
        FONT ='Ubuntu Regular'
        FONTWEIGHT = 'bold' # One of 'ultralight', 'light', 'normal', 'bold',
                            # 'ultrabold', 'heavy', or a numeric weight
        LANG = 'pt' # pt or en
        save_config()

    FONT = FONT + ' ' + FONTSIZE
    
    paddingleft = ClockPadding()
    
    if LANG == 'pt':
        appdayofweek = ClockDayOfWeek()
        appday = ClockDay()
        appmonth = ClockMonth()
    else:
        appdayofweek = ClockDayOfWeek()
        appmonth = ClockMonth()
        appday = ClockDay()

    apptime = ClockTime()

    if LANG != 'pt':
        apptimeampm = ClockTimeAMPM()
        
    paddingright = ClockPadding()
       
    gtk.main()
